<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\ReporterController;
use App\Http\Controllers\EditoralController;
use App\Http\Controllers\LogoController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\SubsubCategoryController;
use App\Http\Controllers\UpazilaController;
use App\Http\Controllers\WebExtraController;
use App\Http\Controllers\VideoController;
use App\Http\Controllers\AdsController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\FrontReporterController;
use App\Http\Controllers\FrontAboutUsController;
use App\Http\Controllers\FrontPrivacyController;
use App\Http\Controllers\Terms_and_ConditionController;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\FrontCategoryNewsController;
use App\Http\Controllers\FrontSubCategoryNewsController;
use App\Http\Controllers\FrontNewsDetailController;
use App\Http\Controllers\PhotoCartController;
use App\Http\Controllers\PrintController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\FrontLatestnewsController;
use App\Http\Controllers\FrontSubSubCategoryController;
use App\Http\Controllers\FrontUpazelasNewsController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\FrontPhotogalleryController;
use App\Http\Controllers\FrontVideoController;

require base_path('routes/admin.php');

Route::get('/mypanel', [LoginController::class, 'index'])->name('login');

Route::get('/', [FrontController::class, 'index'])->name('home');
Route::get('/amader-poribar', [FrontReporterController::class, 'index'])->name('amaderporibar');
Route::get('/reporter-view/{id}/{slug}', [FrontReporterController::class, 'reporter_view'])->name('reporter-view');
Route::get('/about-us', [FrontAboutUsController::class, 'index'])->name('about-us');
Route::get('/privacy-policy', [FrontPrivacyController::class, 'index'])->name('privacy-policy');
Route::get('/terms-and-condition', [Terms_and_ConditionController::class, 'index'])->name('terms-and-condition');
Route::get('/category-news/{id}/{slug}', [FrontCategoryNewsController::class, 'index'])->name('category-news');
Route::get('/sub-category-news/{id}/{slug}', [FrontSubCategoryNewsController::class, 'index'])->name('sub-category-news');
Route::get('/district-news/{id}/{slug}', [FrontSubSubCategoryController::class, 'index'])->name('district-news2');
Route::get('/upazila-news/{id}/{slug}', [FrontUpazelasNewsController::class, 'index'])->name('upazila-news');
Route::get('/news-details/{id}', [FrontNewsDetailController::class, 'index'])->name('news-detail');
Route::get('/news-image/{id}', [FrontNewsDetailController::class, 'ogImage'])->name('news.ogimage');
Route::get('/photo-cart/{id}', [PhotoCartController::class, 'index'])->name('photo-cart');
Route::get('/print/{id}', [PrintController::class, 'index'])->name('print-page');
Route::get('/latest-news', [FrontLatestnewsController::class, 'index'])->name('latest-news');
Route::get('/photo-gallery', [FrontPhotogalleryController::class, 'index'])->name('photo-gallery');
Route::get('/all-video', [FrontVideoController::class, 'index'])->name('all-video');
Route::get('search', [SearchController::class,'index'])->name('search-news');
